version: "3.9"

services:
  jupyter:
    build:
      context: ./jupyter
      dockerfile: dockerfile
    container_name: "jupyter"
    privileged: true
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jupyter:/opt/jupyter/etc"
      - "./shared/etc/passwd:/etc/passwd:ro"
      - "./shared/etc/group:/etc/group:ro"
      - "./shared/etc/shadow:/etc/shadow:ro"
      - "./shared/users:/home"
    ports:
      - '8000:8000'

