version: "3.9"

services:
  jupyter:
    build:
      context: ./jupyter
      dockerfile: dockerfile
    container_name: "jupyter-dev"
    privileged: true
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jupyter:/opt/jupyter/etc/jupyter"
      #- "./shared/etc/passwd:/etc/passwd"
      #- "./shared/etc/shadow:/etc/shadow"
      #- "./shared/etc/group:/etc/group"
      - "./shared/home:/home"
    ports:
      - '8000:8000'

