FROM python:slim-bullseye
USER root
ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /opt/jupyter
RUN python3 -m venv /opt/jupyter
ENV PATH="/opt/jupyter/bin:$PATH:/usr/local/bin"

RUN apt-get update && apt-get install --no-install-recommends --yes apt-utils
RUN apt-get install --no-install-recommends --yes git nodejs npm tzdata
RUN apt-get clean && apt-get autoclean && rm -rf /var/lib/apt/lists/*

RUN npm init -y && npm install -g configurable-http-proxy && rm -rf ~/.npm
RUN ln -s /usr/bin/node /usr/local/bin/node

RUN /opt/jupyter/bin/pip3 install --no-cache-dir --upgrade pip setuptools

## JupyterLab ##
RUN /opt/jupyter/bin/pip3 install --no-cache-dir \
    jupyterlab \
    jupyterlab_code_formatter \
    jupyterlab-git \
    lckr-jupyterlab-variableinspector \
    jupyterlab_widgets \
    ipywidgets \
    black \
    import-ipynb

## JupyterHub ##
RUN /opt/jupyter/bin/pip3 install --no-cache-dir \
    jupyterhub \
    dockerspawner \
    jupyterhub-ldapauthenticator

RUN groupadd -g 1000 jupyter && useradd -m -s /bin/bash -d /home/jupyter -u 1000 -g 1000 jupyter
RUN echo "jupyter:jupyter" | chpasswd

RUN cd /home/jupyter
RUN /opt/jupyter/bin/jupyterhub --generate-config

WORKDIR /home/jupyter/

EXPOSE 8000

CMD ["/opt/jupyter/bin/jupyterhub","-f","jupyterhub_config.py"]
