FROM redhat/ubi8-init:latest
USER root

## Shared resources ##
# RUN dnf -y update && dnf -y install python39 python39-pip nodejs npm libnode64
RUN dnf update -y --disableplugin=subscription-manager && \
    dnf install -y --disableplugin=subscription-manager git python39 python39-pip nodejs npm 
RUN pip3 install --no-cache-dir --upgrade pip setuptools
RUN ln -s /usr/bin/node /usr/local/bin/node
RUN mkdir /root/workspace

## JupyterLab ##
RUN dnf -y install tzdata
RUN pip3 install --no-cache-dir \
    jupyterlab \
    jupyterlab_code_formatter \
    jupyterlab-git \
    lckr-jupyterlab-variableinspector \
    jupyterlab_widgets \
    ipywidgets \
    black \
    import-ipynb

## JupyterHub ##
RUN pip3 install --no-cache-dir \
    jupyterhub \
    dockerspawner \
    jupyterhub-ldapauthenticator

RUN npm init -y && npm install -g configurable-http-proxy

# RUN systemctl enable jupyterhub which doesn't exist
# Alternatively create a symbolic link to a empty file (which should be replaced by the external file)
RUN mkdir -p /usr/local/etc/jupyter/jupyter_hub_config.d
# RUN touch /usr/local/etc/jupyter/jupyter_hub_config.d/jupyterhub.service
# RUN touch /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.service
COPY jupyter_hub_config.d /usr/local/etc/jupyter
COPY jupyter_notebook_config.d /usr/local/etc/jupyter
COPY jupyter_server_config.d /usr/local/etc/jupyter
COPY nbconfig /usr/local/etc/jupyter

# RUN systemctl enable /usr/local/etc/jupyter/jupyter_hub_config.d/jupyterhub.service
RUN ln -s /usr/local/etc/jupyter/jupyter_hub_config.d/jupyterhub.service /etc/systemd/system/jupyterhub.service
RUN ln -s /usr/local/etc/jupyter/jupyter_hub_config.d/jupyterhub.service /etc/systemd/system/multi-user.target.wants/jupyterhub.service
# RUN systemctl enable /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.service
RUN ln -s /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.service /etc/systemd/system/jupyterlab.service
RUN ln -s /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.service /etc/systemd/system/multi-user.target.wants/jupyterlab.service

RUN echo "PATH=\$PATH:/usr/local/bin:/usr/local/sbin">>/etc/profile
RUN echo "export PATH">>/etc/profile

## Clean up the mess ##
RUN rm -rf /var/cache/dnf/* /var/lib/dnf/* /var/log/dnf* /var/log/yum.*
RUN dnf clean all --disableplugin=subscription-manager

CMD ["/sbin/init"]

